### ISSUE TITLE
Images on blog interface not showing

### ISSUE THREAD

**Issue by ikeasamoahansah** [AvinashAnand02/Django-Blog#1]
When you set an image for the blog it does not show

**Comment by AvinashAnand02** [comment]
Thank you for bringing this to my attention. I'll address this issue promptly after my semester exams, which conclude on May 27th.

**Comment by ikeasamoahansah** [comment]
I can fix it. You can assign it to me

**Comment by AvinashAnand02** [comment]
I've assigned it to you, so you can proceed with the task.

**Comment by AvinashAnand02** [comment]
Thank you for your valuable contributions to this project. Your input and efforts are greatly appreciated and make a significant difference. Keep up the great work!
